# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/junki/Downloads/Telegram Desktop/incomplete_cockery.xpr/SoundDisplay/SoundDisplay.srcs/sources_1/ip/bram_4_fft/bram_4_fft.xci
# IP: The module: 'bram_4_fft' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/junki/Downloads/Telegram Desktop/incomplete_cockery.xpr/SoundDisplay/SoundDisplay.srcs/sources_1/ip/bram_4_fft/bram_4_fft_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'bram_4_fft'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: c:/Users/junki/Downloads/Telegram Desktop/incomplete_cockery.xpr/SoundDisplay/SoundDisplay.srcs/sources_1/ip/bram_4_fft/bram_4_fft.xci
# IP: The module: 'bram_4_fft' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/junki/Downloads/Telegram Desktop/incomplete_cockery.xpr/SoundDisplay/SoundDisplay.srcs/sources_1/ip/bram_4_fft/bram_4_fft_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'bram_4_fft'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
